version: "3.9"
services:
  api:
    build: .
    container_name: finance_api
    environment:
      - TZ=America/Recife
    ports:
      - "8000:8000"
    volumes:
      - ./finance.db:/app/finance.db
    restart: always
