version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
 
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV:-production}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES=43200}
      - DATABASE_URL=${DATABASE_URL=sqlite:////data/app.db}
      - CORS_ORIGINS=${ORS_ORIGINS=www.appfinanceiro.domingos-automacoes.shop}
      - FIRST_SUPERUSER_EMAIL=${FIRST_SUPERUSER_EMAIL=fadomingosf@gmail.com}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD=fAdf21mj$}
  
    volumes:
      - data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

# Uncomment to use Postgres instead of SQLite
#  postgres:
#    image: postgres:16
#    container_name: finance-postgres
#    restart: unless-stopped
#    environment:
#      - POSTGRES_DB=financedb
#      - POSTGRES_USER=finance
#      - POSTGRES_PASSWORD=finance
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U finance -d financedb"]
#      interval: 10s
#      timeout: 5s
#      retries: 10

volumes:
  data:
#  pgdata:
