services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      SECRET_KEY: "sua_chave_segura"
      SQLALCHEMY_DATABASE_URI: "sqlite+aiosqlite:///./financeiro.db"
      CORS_ORIGINS: '["https://domingos-automacoes.shop", "https://www.domingos-automacoes.shop"]'
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80"

  proxy:
    image: caddy:2.7
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    restart: always
    ports:
      - "80:80"
      - "443:443"

volumes:
  caddy_data:
  caddy_config:
