version: "3.9"
services:
  db:
    image: postgres:16
    container_name: finance_db
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
      POSTGRES_DB: finance_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [appnet]

  api:
    build: ./backend
    container_name: finance_api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks: [appnet]

  web:
    build: ./frontend
    container_name: finance_web
    depends_on: [api]
    environment:
      - VITE_API_URL=/api/v1
    ports:
      - "8080:80"
    networks: [appnet]

  proxy:
    image: nginx:alpine
    container_name: finance_proxy
    depends_on: [api, web]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks: [appnet]

volumes:
  db_data:

networks:
  appnet:
